version: '3.9'

services:
  database:
    container_name: app_postgres_dev
    image: postgres:12
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    user: postgres
    environment:
        - "POSTGRES_PASSWORD=mysecretpassword"
    networks:
      - app-network
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  # app_server:
  #   container_name: prime-nestjs
  #   image: prime-nestjs:1.0.0
  #   build:
  #     context: .
  #     # target: production
  #     dockerfile: ./Dockerfile
  #   command: npm run start:prod
  #   env_file: .env
  #   ports:
  #     - '3000:3000'
  #     - '9229:9229'
  #   networks:
  #     - app-network
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped
  #   depends_on:
  #     - database

networks:
  app-network:

volumes:
  postgres-data:
